[package]
name = "spell_it_right"
version = "0.1.0"
authors = ["nn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# scan_fmt = "0.2.5"