[package]
name = "mycsv-read-bin"
version = "0.1.0"
authors = ["nn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked-list = "0.0.3"
